conservative_startup:
  name: Conservative Startup
  description: 10-person startup with cautious AI adoption
  baseline:
    profile: startup
  adoption:
    scenario: organic
  impact:
    scenario: conservative
  costs:
    scenario: startup
  timeframe_months: 24
moderate_startup:
  name: Moderate Startup
  description: 10-person startup with balanced adoption approach
  baseline:
    profile: startup
  adoption:
    scenario: grassroots
  impact:
    scenario: moderate
  costs:
    scenario: startup
  timeframe_months: 24
aggressive_startup:
  name: Aggressive Startup
  description: 10-person startup with all-in on AI
  baseline:
    profile: startup
  adoption:
    scenario: mandated
  impact:
    scenario: aggressive
  costs:
    scenario: startup
  timeframe_months: 24
conservative_enterprise:
  name: Conservative Enterprise
  description: 50-person enterprise with cautious AI adoption
  baseline:
    profile: enterprise
  adoption:
    scenario: organic
  impact:
    scenario: conservative
  costs:
    scenario: enterprise
  timeframe_months: 36
moderate_enterprise:
  name: Moderate Enterprise
  description: 50-person enterprise with balanced adoption approach
  baseline:
    profile: enterprise
  adoption:
    scenario: grassroots
  impact:
    scenario: moderate
  costs:
    scenario: enterprise
  timeframe_months: 36
aggressive_enterprise:
  name: Aggressive Enterprise
  description: 50-person enterprise with all-in on AI
  baseline:
    profile: enterprise
  adoption:
    scenario: mandated
  impact:
    scenario: aggressive
  costs:
    scenario: enterprise
  timeframe_months: 36
conservative_scaleup:
  name: Conservative Scaleup
  description: 25-person scale-up with cautious AI adoption
  baseline:
    profile: scale_up
  adoption:
    scenario: organic
  impact:
    scenario: conservative
  costs:
    scenario: aggressive
  timeframe_months: 24
moderate_scaleup:
  name: Moderate Scaleup
  description: 25-person scale-up with balanced adoption approach
  baseline:
    profile: scale_up
  adoption:
    scenario: grassroots
  impact:
    scenario: moderate
  costs:
    scenario: aggressive
  timeframe_months: 24
aggressive_scaleup:
  name: Aggressive Scaleup
  description: 25-person scale-up with all-in on AI
  baseline:
    profile: scale_up
  adoption:
    scenario: mandated
  impact:
    scenario: aggressive
  costs:
    scenario: aggressive
  timeframe_months: 24
custom:
  name: Custom Scenario
  description: User-defined parameters
  baseline:
    team_size: 30
    junior_ratio: 0.33
    mid_ratio: 0.5
    senior_ratio: 0.17
    junior_flc: 130000
    mid_flc: 170000
    senior_flc: 240000
    avg_feature_cycle_days: 20
    avg_bug_fix_hours: 10
    onboarding_days: 40
    defect_escape_rate: 4.0
    production_incidents_per_month: 3
    avg_incident_cost: 8000
    rework_percentage: 0.18
    new_feature_percentage: 0.45
    maintenance_percentage: 0.3
    tech_debt_percentage: 0.1
    meetings_percentage: 0.15
    avg_pr_review_hours: 2.5
    pr_rejection_rate: 0.2
  adoption:
    initial_adopters: 0.08
    early_adopters: 0.18
    early_majority: 0.34
    late_majority: 0.28
    laggards: 0.12
    training_effectiveness: 0.6
    peer_influence: 0.8
    management_mandate: 0.5
    initial_resistance: 0.35
    dropout_rate_month: 0.04
    re_engagement_rate: 0.03
    initial_efficiency: 0.35
    learning_rate: 0.35
    plateau_efficiency: 0.88
    junior_adoption_multiplier: 1.4
    mid_adoption_multiplier: 1.1
    senior_adoption_multiplier: 0.75
  impact:
    feature_cycle_reduction: 0.28
    bug_fix_reduction: 0.38
    onboarding_reduction: 0.45
    pr_review_reduction: 0.55
    defect_reduction: 0.32
    incident_reduction: 0.28
    rework_reduction: 0.45
    feature_capacity_gain: 0.12
    tech_debt_capacity_gain: 0.06
    boilerplate_effectiveness: 0.88
    test_generation_effectiveness: 0.75
    documentation_effectiveness: 0.85
    code_review_effectiveness: 0.65
    debugging_effectiveness: 0.55
    junior_multiplier: 1.6
    mid_multiplier: 1.35
    senior_multiplier: 1.25
  costs:
    cost_per_seat_month: 40
    enterprise_discount: 0.15
    initial_tokens_per_dev_month: 350000
    token_price_per_million: 9
    token_price_decline_annual: 0.28
    token_growth_rate_monthly: 0.12
    token_plateau_month: 10
    initial_training_cost_per_dev: 1200
    ongoing_training_cost_annual: 300
    trainer_cost_per_day: 1800
    training_days_initial: 3
    training_days_ongoing_annual: 1.5
    infrastructure_setup: 15000
    infrastructure_monthly: 1500
    admin_overhead_percentage: 0.03
    context_switch_cost_month: 750
    bad_code_cleanup_percentage: 0.06
    security_review_overhead: 2
    pilot_budget: 25000
    ongoing_experimentation: 15000
  timeframe_months: 30
task_distributions:
  balanced:
    boilerplate: 0.15
    testing: 0.2
    documentation: 0.1
    code_review: 0.15
    debugging: 0.15
    feature_development: 0.2
    refactoring: 0.05
  feature_heavy:
    boilerplate: 0.1
    testing: 0.15
    documentation: 0.05
    code_review: 0.1
    debugging: 0.1
    feature_development: 0.4
    refactoring: 0.1
  maintenance_heavy:
    boilerplate: 0.05
    testing: 0.15
    documentation: 0.15
    code_review: 0.2
    debugging: 0.25
    feature_development: 0.1
    refactoring: 0.1
sensitivity:
  parameters:
  - adoption_rate
  - token_price
  - feature_cycle_reduction
  - defect_reduction
  - cost_per_seat
  ranges:
    adoption_rate:
    - 0.3
    - 0.9
    token_price:
    - 5
    - 15
    feature_cycle_reduction:
    - 0.1
    - 0.5
    defect_reduction:
    - 0.1
    - 0.5
    cost_per_seat:
    - 20
    - 100
