# Sensitivity analysis test scenario for integration testing
sens_scenario:
  name: Sensitivity Analysis Test Scenario
  description: Scenario for sensitivity analysis integration testing
  baseline:
    profile: startup
    team_size: 10
    junior_ratio: 0.4
    mid_ratio: 0.4
    senior_ratio: 0.2
    junior_flc: 100000
    mid_flc: 140000
    senior_flc: 180000
    avg_feature_cycle_days: 15
    avg_bug_fix_hours: 6
    onboarding_days: 30
    defect_escape_rate: 5.0
    production_incidents_per_month: 4
    avg_incident_cost: 5000
    rework_percentage: 0.15
    new_feature_percentage: 0.50
    maintenance_percentage: 0.30
    tech_debt_percentage: 0.10
    meetings_percentage: 0.10
    avg_pr_review_hours: 2.0
    pr_rejection_rate: 0.15
  adoption:
    scenario: organic
    initial_adopters: 0.05
    early_adopters: 0.15
    early_majority: 0.35
    late_majority: 0.30
    laggards: 0.15
    training_effectiveness: 0.7
    peer_influence: 0.6
    management_mandate: 0.3
    initial_resistance: 0.3
    dropout_rate_month: 0.02
    re_engagement_rate: 0.02
    initial_efficiency: 0.40
    learning_rate: 0.3
    plateau_efficiency: 0.85
    junior_adoption_multiplier: 1.3
    mid_adoption_multiplier: 1.0
    senior_adoption_multiplier: 0.8
  impact:
    scenario: moderate
    feature_cycle_reduction: 0.25
    bug_fix_reduction: 0.35
    onboarding_reduction: 0.40
    pr_review_reduction: 0.50
    defect_reduction: 0.30
    incident_reduction: 0.25
    rework_reduction: 0.40
    feature_capacity_gain: 0.10
    tech_debt_capacity_gain: 0.05
    boilerplate_effectiveness: 0.85
    test_generation_effectiveness: 0.70
    documentation_effectiveness: 0.80
    code_review_effectiveness: 0.60
    debugging_effectiveness: 0.50
    junior_multiplier: 1.5
    mid_multiplier: 1.3
    senior_multiplier: 1.2
  costs:
    scenario: startup
    cost_per_seat_month: 30
    enterprise_discount: 0.10
    initial_tokens_per_dev_month: 300000
    token_price_per_million: 10
    token_price_decline_annual: 0.25
    token_growth_rate_monthly: 0.10
    token_plateau_month: 8
    initial_training_cost_per_dev: 1000
    ongoing_training_cost_annual: 250
    trainer_cost_per_day: 1500
    training_days_initial: 2
    training_days_ongoing_annual: 1
    infrastructure_setup: 10000
    infrastructure_monthly: 1000
    admin_overhead_percentage: 0.02
    context_switch_cost_month: 500
    bad_code_cleanup_percentage: 0.05
    security_review_overhead: 1.5
    pilot_budget: 20000
    ongoing_experimentation: 10000
  
  # Sensitivity analysis configuration
  sensitivity:
    parameters:
      - adoption.early_adopters
      - impact.feature_cycle_reduction
      - impact.defect_reduction
      - costs.cost_per_seat_month
      - costs.token_price_per_million
    ranges:
      adoption.early_adopters:
        - 0.10
        - 0.25
      impact.feature_cycle_reduction:
        - 0.15
        - 0.40
      impact.defect_reduction:
        - 0.20
        - 0.45
      costs.cost_per_seat_month:
        - 20
        - 50
      costs.token_price_per_million:
        - 5
        - 20
    
  timeframe_months: 24