# Conservative Strategy
# Cautious approach with lower expectations and slower adoption

name: Conservative Strategy
description: Risk-averse approach with modest expectations

adoption:
  # Adoption curve parameters
  initial_adopters: 0.05
  early_adopters: 0.15
  early_majority: 0.35
  late_majority: 0.30
  laggards: 0.15
  
  # Adoption dynamics
  training_effectiveness: 0.5
  peer_influence: 0.7
  management_mandate: 0.3
  initial_resistance: 0.4
  dropout_rate_month: 0.02
  re_engagement_rate: 0.03
  
  # Learning curve
  initial_efficiency: 0.3
  learning_rate: 0.3
  plateau_efficiency: 0.85
  
  # Segment multipliers
  junior_adoption_multiplier: 1.3
  mid_adoption_multiplier: 1.0
  senior_adoption_multiplier: 0.7

impact:
  # Time improvements
  feature_cycle_reduction: 0.10
  bug_fix_reduction: 0.15
  onboarding_reduction: 0.20
  pr_review_reduction: 0.30
  
  # Quality improvements
  defect_reduction: 0.15
  incident_reduction: 0.10
  rework_reduction: 0.20
  
  # Capacity gains
  feature_capacity_gain: 0.05
  tech_debt_capacity_gain: 0.02
  
  # Task effectiveness
  boilerplate_effectiveness: 0.70
  test_generation_effectiveness: 0.50
  documentation_effectiveness: 0.60
  code_review_effectiveness: 0.40
  debugging_effectiveness: 0.30
  
  # Developer multipliers
  junior_multiplier: 1.3
  mid_multiplier: 1.2
  senior_multiplier: 1.1

costs:
  # Licensing
  cost_per_seat_month: 30
  enterprise_discount: 0.0
  
  # Token usage
  initial_tokens_per_dev_month: 200000
  token_price_per_million: 10
  token_price_decline_annual: 0.3
  token_growth_rate_monthly: 0.15
  token_plateau_month: 9
  
  # Training
  initial_training_cost_per_dev: 500
  ongoing_training_cost_annual: 200
  trainer_cost_per_day: 1500
  training_days_initial: 2
  training_days_ongoing_annual: 1
  
  # Infrastructure
  infrastructure_setup: 5000
  infrastructure_monthly: 500
  admin_overhead_percentage: 0.02
  
  # Hidden costs
  context_switch_cost_month: 500
  bad_code_cleanup_percentage: 0.05
  security_review_overhead: 2
  
  # Experimentation
  pilot_budget: 10000
  ongoing_experimentation: 5000